### ISSUE TITLE
trend line

### ISSUE THREAD

**Issue by Practical-DQ** [danielkagemann/as24#12]
in the Chart it would be good to have another layer call trend line. This line should not fillow the median Point to Point but be a (hopefully) gradual curve showing the Overall tendency

**Comment by danielkagemann** [comment]
so using the average of each "box" or the maximum

**Comment by danielkagemann** [comment]
to get a trend line it might be better to define a timespan for the trend. so maybe makes sense to get a trend line over the years. 
0...12...24...36...48...

**Comment by Practical-DQ** [comment]
Agreed, the trend line should be done over a longer variabl time period 3month/6Month/1 year, and the user shoud be able to choose between max, mean, median or mode

**Comment by danielkagemann** [comment]
the trendline is now on average. gives a better focus on the price and makes more sense using a bigger timespan.

**Comment by Practical-DQ** [comment]
Like it! I would still like to see a choice between max, mean, median and mode. But this is way better

**Comment by danielkagemann** [comment]
switch between 3,6 and 12 month
