### ISSUE TITLE
KM Filter bands

### ISSUE THREAD

**Issue by Practical-DQ** [danielkagemann/as24#26]
Th numbers are to far away for a user to understand. The bands should be
a <15.000 KM p.a.
b 15.000 - 30.000 KM p.a.
c 30.000 - 45.000 KM p.a.
d >45.000 KM p.a.

**Comment by Practical-DQ** [comment]
Sorry for asking you to redo this. but it gives a further Level of granularitry, especially 30-45.000km

**Comment by danielkagemann** [comment]
no problem. no extra costs :-)
