### ISSUE TITLE
putting kilometers into bands

### ISSUE THREAD

**Issue by Practical-DQ** [danielkagemann/as24#8]
divide the total amount on Kilometers driven by the Age (in months) of the car, This would give the amount of Kilometers per month, this assign this into a kilometer bracket, like 
1.000 - 2000 K per month
2.001 - 3.000 K per month
3.001 - 4.000 K per month
4.001 - 5.000 K per month .etc 
This could be used then as a separate filter condition, (where multiple Kilometer filters should be allowed)

**Comment by danielkagemann** [comment]
Displayed in the table. Cannot be used as filter right now.
