### ISSUE TITLE
tagging of description text

### ISSUE THREAD

**Issue by Practical-DQ** [danielkagemann/as24#9]
the description block could be used for tags, with each space making a new tag. The most common tags are then offered to the user to create a filter. 
Eg. From the following description:
2.2 Prime-Line SKYACTIV-D 150 FWD, 110 kW (150 PS)
would be the following tags: 
2.2, 
Prime-Line, 
SKYACTIV-D, 
150, 
FWD, 
100, 
kW, 
150,
PS
Brackets should be ignored as well as upper and lower case

**Comment by danielkagemann** [comment]
Done
